version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - 3000:3000
    volumes:
      - ./:/workspace
    restart: always
    command:
      ["/root/.pyenv/versions/3.10.14/bin/python", "/workspace/src/server.py"]
